-- Optional local Oracle 19c seed data for manual API testing.
-- Apply after schema.sql if JPA_DDL_AUTO=validate.

MERGE INTO OE_LABEL target
USING (SELECT 'MEJUN202601' LABEL_CODE, 'ME Offer' CAMPAIGN_NAME FROM dual) source
ON (target.LABEL_CODE = source.LABEL_CODE)
WHEN NOT MATCHED THEN
    INSERT (LABEL_ID, LABEL_CODE, CAMPAIGN_NAME, DESCRIPTION, STATUS, EXPIRY_DATE, CREATED_AT, CREATED_BY)
    VALUES (OE_LABEL_SEQ.NEXTVAL, source.LABEL_CODE, source.CAMPAIGN_NAME,
            'Merchant electronics offer campaign', 'ACTIVE', DATE '2026-12-31', SYSTIMESTAMP, 'seed');

MERGE INTO OE_MAIN_OFFER_RECORD target
USING (SELECT 'SEQ-10001' SEQUENCE_NUMBER FROM dual) source
ON (target.SEQUENCE_NUMBER = source.SEQUENCE_NUMBER)
WHEN NOT MATCHED THEN
    INSERT (RECORD_ID, SEQUENCE_NUMBER, LABEL_CODE, CAMPAIGN_NAME, AAN, MOBILE_NUMBER,
            EMAIL_ID, MERCHANT_ID, VALIDITY_DATE, OFFER_TEXT, OFFER_TNC, STATUS, UPDATED_AT, UPDATED_BY)
    VALUES (OE_MAIN_OFFER_SEQ.NEXTVAL, source.SEQUENCE_NUMBER, 'MEJUN202601', 'ME Offer', 'AAN1',
            '999XXXXXXX', 'def@example.com', 'A012', DATE '2026-12-31',
            'Spend Rs 20000 and get a voucher on your HDFC Bank Credit Card',
            'https://www.smartbuy.example/tnc', 'ACTIVE', SYSTIMESTAMP, 'seed');

-- Normalized customer inquiry sample aligned to the uploaded offer file structure.
DELETE FROM OE_OFFER_DETAIL WHERE CUSTOMER_RECORD_ID IN (
    SELECT CUSTOMER_RECORD_ID FROM OE_OFFER_CUSTOMER WHERE SOURCE_SEQUENCE_NUMBER IN ('SRC-10001','SRC-10002')
);
DELETE FROM OE_OFFER_MERCHANT_KEY WHERE CUSTOMER_RECORD_ID IN (
    SELECT CUSTOMER_RECORD_ID FROM OE_OFFER_CUSTOMER WHERE SOURCE_SEQUENCE_NUMBER IN ('SRC-10001','SRC-10002')
);
DELETE FROM OE_OFFER_CUSTOMER WHERE SOURCE_SEQUENCE_NUMBER IN ('SRC-10001','SRC-10002');

INSERT INTO OE_OFFER_CUSTOMER (
    CUSTOMER_RECORD_ID, SOURCE_SEQUENCE_NUMBER, LABEL_CODE, CAMPAIGN_NAME, AAN, MOBILE_NUMBER,
    EMAIL_ID, KEY_FIELD_3, KEY_FIELD_4, KEY_FIELD_5, STATUS, CREATED_AT
) VALUES (
    OE_OFFER_CUSTOMER_SEQ.NEXTVAL, 'SRC-10001', 'MEJUN202601', 'ME Offer', 'AAN1',
    '999XXXXXXX', 'def@example.com', 'KF3-001', 'KF4-001', 'KF5-001', 'ACTIVE', SYSTIMESTAMP
);

INSERT INTO OE_OFFER_CUSTOMER (
    CUSTOMER_RECORD_ID, SOURCE_SEQUENCE_NUMBER, LABEL_CODE, CAMPAIGN_NAME, AAN, MOBILE_NUMBER,
    EMAIL_ID, KEY_FIELD_3, KEY_FIELD_4, KEY_FIELD_5, STATUS, CREATED_AT
) VALUES (
    OE_OFFER_CUSTOMER_SEQ.NEXTVAL, 'SRC-10002', 'MEJUN202601', 'ME Offer', 'AAN1001',
    '9876543210', 'customer1@test.com', 'KF3-002', 'KF4-002', 'KF5-002', 'ACTIVE', SYSTIMESTAMP
);

INSERT INTO OE_OFFER_MERCHANT_KEY (MERCHANT_KEY_ID, CUSTOMER_RECORD_ID, MERCHANT_SEQUENCE, MERCHANT_NAME, MERCHANT_ID)
SELECT OE_OFFER_MERCHANT_KEY_SEQ.NEXTVAL, CUSTOMER_RECORD_ID, 1, 'Amazon', 'A012'
FROM OE_OFFER_CUSTOMER WHERE SOURCE_SEQUENCE_NUMBER = 'SRC-10001';

INSERT INTO OE_OFFER_MERCHANT_KEY (MERCHANT_KEY_ID, CUSTOMER_RECORD_ID, MERCHANT_SEQUENCE, MERCHANT_NAME, MERCHANT_ID)
SELECT OE_OFFER_MERCHANT_KEY_SEQ.NEXTVAL, CUSTOMER_RECORD_ID, 2, 'Flipkart', 'F012'
FROM OE_OFFER_CUSTOMER WHERE SOURCE_SEQUENCE_NUMBER = 'SRC-10001';

INSERT INTO OE_OFFER_MERCHANT_KEY (MERCHANT_KEY_ID, CUSTOMER_RECORD_ID, MERCHANT_SEQUENCE, MERCHANT_NAME, MERCHANT_ID)
SELECT OE_OFFER_MERCHANT_KEY_SEQ.NEXTVAL, CUSTOMER_RECORD_ID, 1, 'Amazon', 'AMAZON'
FROM OE_OFFER_CUSTOMER WHERE SOURCE_SEQUENCE_NUMBER = 'SRC-10002';

INSERT INTO OE_OFFER_DETAIL (OFFER_DETAIL_ID, CUSTOMER_RECORD_ID, OFFER_SEQUENCE, OFFER_TEXT, OFFER_START_DATE, OFFER_END_DATE, OFFER_TNC_URL, STATUS)
SELECT OE_OFFER_DETAIL_SEQ.NEXTVAL, CUSTOMER_RECORD_ID, 1,
       'Spend Rs 20000 and get Rs 500 voucher on eligible HDFC Bank Credit Card transaction',
       DATE '2026-01-01', DATE '2026-12-31', 'https://www.smartbuy.example/tnc', 'ACTIVE'
FROM OE_OFFER_CUSTOMER WHERE SOURCE_SEQUENCE_NUMBER = 'SRC-10001';

INSERT INTO OE_OFFER_DETAIL (OFFER_DETAIL_ID, CUSTOMER_RECORD_ID, OFFER_SEQUENCE, OFFER_TEXT, OFFER_START_DATE, OFFER_END_DATE, OFFER_TNC_URL, STATUS)
SELECT OE_OFFER_DETAIL_SEQ.NEXTVAL, CUSTOMER_RECORD_ID, 2,
       'Do one contactless transaction and get Rs 50 voucher',
       DATE '2026-01-01', DATE '2026-12-31', 'https://www.smartbuy.example/contactless-tnc', 'ACTIVE'
FROM OE_OFFER_CUSTOMER WHERE SOURCE_SEQUENCE_NUMBER = 'SRC-10001';

INSERT INTO OE_OFFER_DETAIL (OFFER_DETAIL_ID, CUSTOMER_RECORD_ID, OFFER_SEQUENCE, OFFER_TEXT, OFFER_START_DATE, OFFER_END_DATE, OFFER_TNC_URL, STATUS)
SELECT OE_OFFER_DETAIL_SEQ.NEXTVAL, CUSTOMER_RECORD_ID, 1,
       '10 percent cashback on Amazon transaction',
       DATE '2026-01-01', DATE '2026-12-31', 'https://www.smartbuy.example/amazon-tnc', 'ACTIVE'
FROM OE_OFFER_CUSTOMER WHERE SOURCE_SEQUENCE_NUMBER = 'SRC-10002';

COMMIT;
