-- Oracle 19c schema for CR_12-05-2026 Offer Engine PoC.
-- Apply as OFFERENGINE user or adjust schema prefixes.
-- The application can also create/update these objects locally with JPA_DDL_AUTO=update.

CREATE SEQUENCE OE_LABEL_SEQ START WITH 1 INCREMENT BY 50 NOCACHE;
CREATE SEQUENCE OE_MAIN_OFFER_SEQ START WITH 1 INCREMENT BY 50 NOCACHE;
CREATE SEQUENCE OE_API_PAYLOAD_LOG_SEQ START WITH 1 INCREMENT BY 50 NOCACHE;

CREATE TABLE OE_LABEL (
    LABEL_ID NUMBER(19) NOT NULL,
    LABEL_CODE VARCHAR2(50 CHAR) NOT NULL,
    CAMPAIGN_NAME VARCHAR2(100 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(500 CHAR),
    STATUS VARCHAR2(20 CHAR) NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(50 CHAR) NOT NULL,
    UPDATED_AT TIMESTAMP,
    UPDATED_BY VARCHAR2(50 CHAR),
    CONSTRAINT PK_OE_LABEL PRIMARY KEY (LABEL_ID),
    CONSTRAINT UK_OE_LABEL_CODE UNIQUE (LABEL_CODE)
);

CREATE TABLE OE_MAIN_OFFER_RECORD (
    RECORD_ID NUMBER(19) NOT NULL,
    SEQUENCE_NUMBER VARCHAR2(50 CHAR) NOT NULL,
    LABEL_CODE VARCHAR2(50 CHAR) NOT NULL,
    CAMPAIGN_NAME VARCHAR2(100 CHAR) NOT NULL,
    AAN VARCHAR2(50 CHAR),
    MOBILE_NUMBER VARCHAR2(50 CHAR),
    EMAIL_ID VARCHAR2(100 CHAR),
    MERCHANT_ID VARCHAR2(50 CHAR),
    VALIDITY_DATE DATE NOT NULL,
    OFFER_TEXT VARCHAR2(250 CHAR),
    OFFER_TNC VARCHAR2(500 CHAR),
    STATUS VARCHAR2(20 CHAR) NOT NULL,
    UPDATED_AT TIMESTAMP,
    UPDATED_BY VARCHAR2(50 CHAR),
    CONSTRAINT PK_OE_MAIN_OFFER_RECORD PRIMARY KEY (RECORD_ID),
    CONSTRAINT UK_OE_MAIN_OFFER_SEQ UNIQUE (SEQUENCE_NUMBER)
);

CREATE TABLE OE_API_PAYLOAD_LOG (
    LOG_ID NUMBER(19) NOT NULL,
    API_NAME VARCHAR2(100 CHAR) NOT NULL,
    HTTP_METHOD VARCHAR2(10 CHAR) NOT NULL,
    REQUEST_PATH VARCHAR2(200 CHAR) NOT NULL,
    REQUEST_PAYLOAD CLOB,
    RESPONSE_PAYLOAD CLOB,
    CREATED_AT TIMESTAMP NOT NULL,
    PURGE_AFTER TIMESTAMP NOT NULL,
    CONSTRAINT PK_OE_API_PAYLOAD_LOG PRIMARY KEY (LOG_ID)
);

CREATE INDEX IDX_OE_LABEL_STATUS_EXPIRY ON OE_LABEL (STATUS, EXPIRY_DATE);
CREATE INDEX IDX_OE_MAIN_OFFER_LOOKUP
    ON OE_MAIN_OFFER_RECORD (CAMPAIGN_NAME, STATUS, VALIDITY_DATE, AAN, MOBILE_NUMBER, EMAIL_ID, MERCHANT_ID);
CREATE INDEX IDX_OE_PAYLOAD_LOG_PURGE ON OE_API_PAYLOAD_LOG (PURGE_AFTER);
