WHENEVER SQLERROR EXIT SQL.SQLCODE
SET SERVEROUTPUT ON

ALTER SESSION SET CONTAINER = ORCLPDB;

DECLARE
    user_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO user_count
    FROM dba_users
    WHERE username = 'OFFERENGINE';

    IF user_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER OFFERENGINE IDENTIFIED BY offerengine DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS';
        DBMS_OUTPUT.PUT_LINE('Created user OFFERENGINE');
    ELSE
        DBMS_OUTPUT.PUT_LINE('User OFFERENGINE already exists');
    END IF;
END;
/

GRANT CREATE SESSION TO OFFERENGINE;
GRANT CREATE TABLE TO OFFERENGINE;
GRANT CREATE SEQUENCE TO OFFERENGINE;
GRANT CREATE VIEW TO OFFERENGINE;
GRANT CREATE PROCEDURE TO OFFERENGINE;
GRANT UNLIMITED TABLESPACE TO OFFERENGINE;

EXIT
