WHENEVER SQLERROR EXIT SQL.SQLCODE
SET SERVEROUTPUT ON

MERGE INTO OE_LABEL target
USING (
    SELECT 'MEJUN202601' LABEL_CODE, 'ME Offer' CAMPAIGN_NAME FROM dual
) source
ON (target.LABEL_CODE = source.LABEL_CODE)
WHEN NOT MATCHED THEN
    INSERT (
        LABEL_ID, LABEL_CODE, CAMPAIGN_NAME, DESCRIPTION, STATUS, EXPIRY_DATE,
        CREATED_AT, CREATED_BY
    )
    VALUES (
        OE_LABEL_SEQ.NEXTVAL, source.LABEL_CODE, source.CAMPAIGN_NAME,
        'Merchant electronics offer campaign', 'ACTIVE', DATE '2026-12-31',
        SYSTIMESTAMP, 'seed'
    )
/

MERGE INTO OE_MAIN_OFFER_RECORD target
USING (
    SELECT 'SEQ-10001' SEQUENCE_NUMBER FROM dual
) source
ON (target.SEQUENCE_NUMBER = source.SEQUENCE_NUMBER)
WHEN NOT MATCHED THEN
    INSERT (
        RECORD_ID, SEQUENCE_NUMBER, LABEL_CODE, CAMPAIGN_NAME, AAN, MOBILE_NUMBER,
        EMAIL_ID, MERCHANT_ID, VALIDITY_DATE, OFFER_TEXT, OFFER_TNC, STATUS, UPDATED_AT, UPDATED_BY
    )
    VALUES (
        OE_MAIN_OFFER_SEQ.NEXTVAL, source.SEQUENCE_NUMBER, 'MEJUN202601', 'ME Offer',
        'AAN1', '999XXXXXXX', 'def@example.com', 'A012', DATE '2026-12-31',
        'Spend Rs 20000 and get a voucher on your HDFC Bank Credit Card',
        'https://www.smartbuy.example/tnc', 'ACTIVE', SYSTIMESTAMP, 'seed'
    )
/

COMMIT
/

EXIT
