WHENEVER SQLERROR EXIT SQL.SQLCODE
SET SERVEROUTPUT ON

CREATE SEQUENCE OE_OFFER_CUSTOMER_SEQ START WITH 1 INCREMENT BY 50 NOCACHE
/
CREATE SEQUENCE OE_OFFER_MERCHANT_KEY_SEQ START WITH 1 INCREMENT BY 50 NOCACHE
/
CREATE SEQUENCE OE_OFFER_DETAIL_SEQ START WITH 1 INCREMENT BY 50 NOCACHE
/

CREATE TABLE OE_OFFER_CUSTOMER (
    CUSTOMER_RECORD_ID NUMBER(19) NOT NULL,
    SOURCE_SEQUENCE_NUMBER VARCHAR2(50 CHAR) NOT NULL,
    LABEL_CODE VARCHAR2(50 CHAR) NOT NULL,
    CAMPAIGN_NAME VARCHAR2(100 CHAR) NOT NULL,
    AAN VARCHAR2(50 CHAR),
    MOBILE_NUMBER VARCHAR2(50 CHAR),
    EMAIL_ID VARCHAR2(100 CHAR),
    KEY_FIELD_3 VARCHAR2(50 CHAR),
    KEY_FIELD_4 VARCHAR2(50 CHAR),
    KEY_FIELD_5 VARCHAR2(50 CHAR),
    STATUS VARCHAR2(20 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT PK_OE_OFFER_CUSTOMER PRIMARY KEY (CUSTOMER_RECORD_ID),
    CONSTRAINT UK_OE_OFFER_CUSTOMER_SEQ UNIQUE (SOURCE_SEQUENCE_NUMBER)
)
/

CREATE TABLE OE_OFFER_MERCHANT_KEY (
    MERCHANT_KEY_ID NUMBER(19) NOT NULL,
    CUSTOMER_RECORD_ID NUMBER(19) NOT NULL,
    MERCHANT_SEQUENCE NUMBER(3) NOT NULL,
    MERCHANT_NAME VARCHAR2(100 CHAR),
    MERCHANT_ID VARCHAR2(50 CHAR),
    CONSTRAINT PK_OE_OFFER_MERCHANT_KEY PRIMARY KEY (MERCHANT_KEY_ID),
    CONSTRAINT FK_OE_MERCHANT_CUSTOMER FOREIGN KEY (CUSTOMER_RECORD_ID)
        REFERENCES OE_OFFER_CUSTOMER (CUSTOMER_RECORD_ID)
)
/

CREATE TABLE OE_OFFER_DETAIL (
    OFFER_DETAIL_ID NUMBER(19) NOT NULL,
    CUSTOMER_RECORD_ID NUMBER(19) NOT NULL,
    OFFER_SEQUENCE NUMBER(3) NOT NULL,
    OFFER_TEXT VARCHAR2(1000 CHAR),
    OFFER_START_DATE DATE,
    OFFER_END_DATE DATE NOT NULL,
    OFFER_TNC_URL VARCHAR2(500 CHAR),
    STATUS VARCHAR2(20 CHAR) NOT NULL,
    CONSTRAINT PK_OE_OFFER_DETAIL PRIMARY KEY (OFFER_DETAIL_ID),
    CONSTRAINT FK_OE_DETAIL_CUSTOMER FOREIGN KEY (CUSTOMER_RECORD_ID)
        REFERENCES OE_OFFER_CUSTOMER (CUSTOMER_RECORD_ID)
)
/

CREATE INDEX IDX_OE_OFFER_CUSTOMER_LOOKUP ON OE_OFFER_CUSTOMER (
    CAMPAIGN_NAME, STATUS, LABEL_CODE, AAN, MOBILE_NUMBER, EMAIL_ID, KEY_FIELD_3, KEY_FIELD_4, KEY_FIELD_5
)
/
CREATE INDEX IDX_OE_MERCHANT_LOOKUP ON OE_OFFER_MERCHANT_KEY (CUSTOMER_RECORD_ID, MERCHANT_ID, MERCHANT_NAME)
/
CREATE INDEX IDX_OE_OFFER_DETAIL_LIVE ON OE_OFFER_DETAIL (CUSTOMER_RECORD_ID, STATUS, OFFER_START_DATE, OFFER_END_DATE)
/

COMMIT
/

EXIT
